/* eslint-disable import/prefer-default-export */
export const departureActionTypes = {
  GET_DEPARTURE_TIMES: 'GET_DEPARTURE_TIMES',
  GET_INBOUND_DEPARTURE_TIME: 'GET_INBOUND_DEPARTURE_TIME',
  SET_INBOUND_DEPARTURE_TIME: 'SET_INBOUND_DEPARTURE_TIME',
  UNSET_INBOUND_DEPARTURE_TIME: 'UNSET_INBOUND_DEPARTURE_TIME',
  GET_OUTBOUND_DEPARTURE_TIME: 'GET_OUTBOUND_DEPARTURE_TIME',
  SET_OUTBOUND_DEPARTURE_TIME: 'SET_OUTBOUND_DEPARTURE_TIME',
  UNSET_OUTBOUND_DEPARTURE_TIME: 'UNSET_OUTBOUND_DEPARTURE_TIME'
}
