/* eslint-disable import/prefer-default-export */
export const stationsActionTypes = {
  FIND_STATION: 'FIND_STATION',
  SET_STATION: 'SET_STATION',
  UNSET_STATION: 'UNSET_STATION',
  SET_LATITUDE: 'SET_LATITUDE',
  SET_LONGITUDE: 'SET_LONGITUDE',
  UNSET_LATLONG: 'UNSET_LATLONG',
  UPDATE_FETCH_STATUS: 'UPDATE_FETCH_STATUS'
}
