service: code-challange-api
custom:
  stage:  ${opt:stage, self:provider.stage}
  defaultProfile: default
  defaultRegion: ap-northeast-1
  logRetentionInDays:
    development: "14"  # stage[development]は14日
    production: "90"   # stage[production]は90日
    default: "3"       # stageが見つからなかったらこれにfallbackするために設定
  memorySize:
    development: 128   # stage[development]は256M
    production: 512    # stage[production]は512M
    default: 128       # stageが見つからなかったらこれにfallbackするために設定

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 30
  stage: development
  memorySize: ${self:custom.memorySize.${self:custom.stage}, self:custom.memorySize.default}
  profile: ${opt:profile, self:custom.defaultProfile}
  region: ${opt:region, self:custom.defaultRegion}
  deploymentBucket: serverless.${self:provider.region}.hideokamoto.deploys

package:
  exclude:
    - tests/**
    - .DS_Store
    - circle.yml
    - package.json
    - event.json
    - .git/**
    - .serverless/**
    - .editorconfig
    - .eslintrc.yml
    - coverage/**

functions:
  station:
    handler: handler.station
    events:
      - http:
          path: station/{name}
          method: get
      - http:
          path: station/search
          method: get
          request:
            parameters:
              querystrings:
                lat: true
                long: true
  departure:
    handler: handler.departure
    events:
      - http:
          path: departure/{lineName}/{station}
          method: get
          request:
            parameters:
              querystrings:
                lineType: false
                timestamp: false

resources:
  Resources:
    StationLogGroup:
      Properties:
        RetentionInDays: ${self:custom.logRetentionInDays.${self:custom.stage}, self:custom.logRetentionInDays.default}
    DepartureLogGroup:
      Properties:
        RetentionInDays: ${self:custom.logRetentionInDays.${self:custom.stage}, self:custom.logRetentionInDays.default}

plugins:
  - serverless-prune-plugin
